# Generated by Django 2.2 on 2021-06-19 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmodel',
            old_name='_answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='questionmodel',
            old_name='_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questionmodel',
            old_name='_value',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='responsemodel',
            old_name='_username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='responsemodel',
            old_name='_value',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='_total',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='resultmodel',
            old_name='_username',
            new_name='username',
        ),
    ]
