# Generated by Django 2.2 on 2021-07-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='vanity',
            field=models.IntegerField(),
        ),
    ]
