# Generated by Django 2.2 on 2021-06-21 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210619_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsemodel',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.QuestionModel'),
        ),
    ]
