# Generated by Django 2.2 on 2021-07-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210701_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultmodel',
            name='feature',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
