# Generated by Django 2.2 on 2021-07-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_resultmodel_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmodel',
            name='feature',
            field=models.CharField(choices=[('authoritarianism', 'authoritarianism'), ('exhibitionism', 'exhibitionism'), ('superiority', 'superiority'), ('claim', 'claim'), ('unscrupulous', 'unscrupulous'), ('selfsufficiency', 'selfsufficiency'), ('vanity', 'vanity')], max_length=20, null=True),
        ),
    ]
